// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// assign_to_layer
CharacterVector assign_to_layer(const DataFrame& df);
RcppExport SEXP _rectanglePacking_assign_to_layer(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(assign_to_layer(df));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rectanglePacking_assign_to_layer", (DL_FUNC) &_rectanglePacking_assign_to_layer, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rectanglePacking(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
